repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
  - repo: "https://github.com/pre-commit/mirrors-autopep8"
    rev: v2.0.2
    hooks:
      - id: autopep8
        args:
          - "--diff"
          - "--ignore=E501,W503,E203"
  - repo: "https://github.com/psf/black"
    rev: 23.3.0
    hooks:
      - id: black
        exclude: migrations/
        args:
          - "--skip-magic-trailing-comma"
        language_version: python3.10.9
  - repo: "https://github.com/PyCQA/flake8"
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: migrations/
        args:
          - "--ignore=E501,W503,E203,E211"
  - repo: "https://github.com/pycqa/isort"
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: migrations/
        args:
          - "--profile"
          - black
